--1229
SELECT *
FROM all_users;

--SCOTT:사용자 / TIGER:비밀번호 / 일반사용자권한

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER scott
IDENTIFIED BY tiger
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE
TO scott; -- 권한을 부여

CREATE USER hr
IDENTIFIED BY hr
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE
TO hr;